### ISSUE TITLE
[autopilot] Support pandas 3.x: lift the <3.0.0 cap and fix the two calls that break under it

### ISSUE THREAD

**Issue by wdm0006** [wdm0006/git-pandas#75]
## Problem

`pyproject.toml` pins `pandas>=2.0.0,<3.0.0`. pandas 3.0 has been out for a while (3.0.5 is current on PyPI), so a plain `pip install git-pandas` now either downgrades a user's pandas or fails to resolve at all in any environment that already wants pandas 3. That makes the library effectively uninstallable for new users on a current stack.

I ran the full suite against `pandas==3.0.5` on Python 3.12 (`uv pip install "pandas==3.0.5" ... --no-deps -e .`, then `MPLBACKEND=Agg pytest -m "not slow"`):

```
11 failed, 422 passed, 1 deselected
```

The 11 failures collapse to **two real source bugs** plus **two test-side dtype assertions**. I also swept every public `Repository` / `ProjectDirectory` method under pandas 3 against a two-repo fixture; apart from `hours_estimate`, everything else (`commit_history`, `file_change_history`, `file_change_rates`, `blame`, `revs`, `cumulative_blame`, `parallel_cumulative_blame`, `tags`, `commits_in_tags`, `bus_factor`, `punchcard`, `file_detail`, `release_tag_summary`, the rev-to-rev family) returns the same shapes it does on pandas 2. So the surface area is genuinely small.

### 1. `hours_estimate` raises `TypeError` (`gitpandas/repository.py`, in `hours_estimate`)

```python
commits_ts = [x * 10e-10 for x in sorted(commits.index.values.tolist())]
```

On pandas 2, `DatetimeIndex.values.tolist()` yields `int` nanoseconds. On pandas 3 it yields `datetime.datetime` objects, so:

```
TypeError: unsupported operand type(s) for *: 'datetime.datetime' and 'float'
```

`Repository.hours_estimate` and `ProjectDirectory.hours_estimate` both fail outright. Verified fix — `idx.astype("int64").tolist()` returns the *identical* integer list on pandas 2.3.3 and works on 3.0.5:

```
pandas 2.3.3  values.tolist(): [1700000000000000000, 1700003600000000000]
pandas 2.3.3  astype int64   : [1700000000000000000, 1700003600000000000]   equal: True
pandas 3.0.5  values.tolist(): [datetime.datetime(2023, 11, 14, 22, 13, 20)]
pandas 3.0.5  astype int64   : [1700000000, ...]  (ns, works)
```

### 2. `plot_lifeline` raises `AttributeError` (`gitpandas/utilities/plotting.py`, in `plot_lifeline`)

```python
files = changes.filename.unique()
files.sort()
```

pandas 3 makes `str` the default dtype, so `.unique()` returns a `StringArray`, which has no in-place `.sort()`:

```
AttributeError: 'StringArray' object has no attribute 'sort'
```

Accounts for 5 of the 11 failures. `sorted(...)` / `np.sort(...)` works on both.

### 3. Test-side dtype assertions (2 failures)

`tests/test_Repository/test_edge_cases.py::TestRepositoryDataValidation::test_commit_history_data_types` and the `ProjectDirectory` sibling assert `history[col].dtype == object` for string columns. Under pandas 3 the dtype is `StringDtype(storage='python', na_value=nan)`. The frames are correct; the assertion is over-specific.

## Proposed change

Single PR, no restructuring:

1. `gitpandas/repository.py` — build `commits_ts` from `commits.index.astype("int64")` instead of `.values.tolist()`. Byte-identical behaviour on pandas 2.
2. `gitpandas/utilities/plotting.py` — sort the unique filenames with a dtype-agnostic call instead of the in-place ndarray `.sort()`.
3. `pyproject.toml` — relax to `pandas>=2.0.0` (drop the upper cap). pandas 3 requires Python >= 3.11, so resolvers on the declared 3.10 floor keep picking pandas 2.x automatically; no environment marker is needed.
4. Test dtype assertions — accept either `object` or pandas' string dtype (`pd.api.types.is_string_dtype`) rather than pinning `== object`.
5. `.github/workflows/test-suite.yml` — add one job (or matrix entry) that installs `pandas>=3` explicitly on Python 3.12 and runs the same `pytest -m "not slow"` + `ruff check .` steps, so the pandas-2 and pandas-3 paths are both gated. Without this the cap can silently re-rot.
6. `CHANGELOG.md` — new `### pandas 3 Compatibility` area heading under `Unreleased`.

Value assertions for `hours_estimate` already exist (`tests/test_Repository/test_hours_estimate.py`, pinned timestamps) and will cover the fix on both majors once the CI job is in place; no new fixture needed there.

## Acceptance

- [ ] `MPLBACKEND=Agg pytest -m "not slow"` passes with `pandas==2.3.x` installed (currently 433 passed, 1 deselected — no regression).
- [ ] `MPLBACKEND=Agg pytest -m "not slow"` passes with `pandas>=3.0` installed (currently 11 failed).
- [ ] `grep -n "pandas" pyproject.toml` shows no `<3` upper bound.
- [ ] `hours_estimate` returns the same per-committer values on pandas 2 and pandas 3 for a fixture with `GIT_AUTHOR_DATE`/`GIT_COMMITTER_DATE` pinned (the existing `test_hours_estimate.py` fixture is enough).
- [ ] Reverting only the `repository.py` line makes the `hours_estimate` tests fail under pandas 3; reverting only the `plotting.py` line makes the `plot_lifeline` tests fail. State both results in the PR body.
- [ ] CI runs the suite against pandas 3 on at least one matrix entry, and that entry is red without the source fixes.
- [ ] `ruff check .` clean.

## Risk

low/medium — low on the source side: both fixes are one-liners whose pandas-2 output is verified identical, and the pandas-3 surface was swept method-by-method rather than inferred from the suite alone. The medium part is the dependency cap: lifting it means a user's resolver may now pull pandas 3 where it previously could not, so the pandas-3 CI job is the part that has to actually land, not just the pin change.

**Comment by wdm0006** [comment]
autopilot: implementation attempt did not open a PR (rc=1). See operator logs: `implement.wdm0006_git-pandas.75.20260806-150223.log`. Will not retry until re-approved (remove the `autopilot:blocked` label and re-add `autopilot:approved`).

**Comment by wdm0006** [comment]
autopilot: implementation attempt did not open a PR (rc=1). See operator logs: `implement.wdm0006_git-pandas.75.20260807-202617.log`. Will not retry until re-approved (remove the `autopilot:blocked` label and re-add `autopilot:approved`).
